import type { Metadata } from "next"
import localFont from "next/font/local"
import { Provider } from "@/components/ui/provider"
import "./globals.css"
import ReactQueryProviderClient from "@/lib/providers/ReactQueryProviderClient"

const geistSans = localFont({
  src: "../node_modules/next/dist/client/components/react-dev-overlay/font/geist-latin.woff2",
  variable: "--font-geist-sans",
})

const geistMono = localFont({
  src: "../node_modules/next/dist/client/components/react-dev-overlay/font/geist-mono-latin.woff2",
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ReactQueryProviderClient>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable}`}
        >
          <Provider>{children}</Provider>
        </body>
      </html>
    </ReactQueryProviderClient>
  )
}
